// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieApp.Models;

namespace MovieApp.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    partial class MovieDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MovieApp.Models.MovieDetails", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Director")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovieGenre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovieName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("MovieId");

                    b.ToTable("movieDetails");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Director = "Ari Aster",
                            MovieGenre = "Horror",
                            MovieName = "Heriditary",
                            Price = 150
                        },
                        new
                        {
                            MovieId = 2,
                            Director = "Ari Aster",
                            MovieGenre = "Horror",
                            MovieName = "Midsommar",
                            Price = 250
                        },
                        new
                        {
                            MovieId = 3,
                            Director = "Lin-Manuel Miranda",
                            MovieGenre = "Horror",
                            MovieName = "Tick,Tick...Boom!",
                            Price = 350
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
